levels = {
    "wHEwIEwJEwKEwLEwMEwNEwOEwPEwQEwREwSEwTEwUEwGFwHFhTFIwUFwGGpKGhTGJwUGwGHwNHwOHwPHhTHBwUHwGIwHIbIIAbKIAbMIAwNIwPIwQIwRIwSIwTIwUIwHJwNJwHKwIKwJKwKKwLKwMKwNK",
    "wHEwIEwJEwKEwLEwMEwNEwOEwPEwQEwREwSEwTEwHFhSFIwTFwHGpJGcLGBhSGJwTGwHHwOHhSHBwTHwHIbIIAbKIAbMIAwOIwPIwQIwRIwSIwTIwHJwOJwHKwIKwJKwKKwLKwMKwNKwOK",
    "wGEwHEwIEwJEwKEwLEwMEwNEwOEwPEwQEwREwSEwTEwUEwGFwLFbMFBwNFbOFBwSFwTFwUFwGGbNGBbPGBwSGwTGwUGwGHpHHbIHAbMHBbOHBhTHAwUHwGIbNIBbPIBwSIwTIwUIwGJwNJbOJBwSJwTJwUJwGKwHKwIKwJKwKKwLKwMKwNKwOKwPKwQKwRKwSKwTKwUK",
    "wHEwIEwJEwKEwHFwKFwLFwMFwNFwOFwPFwQFwRFwSFwTFwHGbLGAcOGBhSGIwTGwHHpJHbLHAhSHBwTHwHIbLIAhSIAwTIwHJwKJwLJwMJwNJwOJwPJwQJwRJwSJwTJwHKwIKwJKwKK",
    "wPEwQEwREwSEwTEwFFwGFwHFwIFwJFwKFwLFwMFwOFwPFwTFwUFwFGcIGBbKGAbLGAwMGwNGwOGhPGEhQGOhRGKwUGwFHbJHAbKHAbLHAhQHFhRHDwUHwFIwMIwNIdQIIpSIwUIwFJwGJwHJwIJwJJwKJwLJwMJwNJwOJdQJBwUJwOKwPKwTKwUKwPLwQLwRLwSLwTL",
    "wKDwLDwMDwNDwODwKEwOEwPEwQEwREwSEwTEwGFwHFwIFwJFwKFwMFwOFwPFhSFAwTFwGGwKGwMGwOGwPGwSGwTGwGHpHHbIHAbMHAhSHAwTHwGIwKIwMIbNIAwOIwPIwSIwTIwGJwHJwIJwJJwKJwMJwOJwPJhSJAwTJwKKwOKwPKwQKwRKwSKwTKwKLwLLwMLwNLwOL",
    "wLCwMCwNCwLDbMDAwNDwODwPDwQDwKEwLEwNEwQEwGFwHFwIFwJFwKFbLFBbMFBbNFBbOFCwQFwGGhIGEhJGGhKGCwQGwGHpHHhIHAhJHAhKHAwQHwGIhIIAhJIAhKIAwQIwGJwHJwIJwJJwKJwLJwNJwPJwQJwKKbLKBbPKAwQKwKLwLLbMLAwNLbOLBwPLwQLwLMwMMwNMwOMwPM",
    "wGBwHBwIBwJBwKBwLBwMBwNBwOBwPBwGCwPCwGDhLDIhMDEhNDCwPDwGEhLEJhMEEhNEKwPEwGFpJFhLFBhNFBwPFwGGhLGEhMGChNGAwPGwGHwHHwIHwJHwKHwPHwHIbIIBbJIBbKICbLICbMIAwPIwHJwIJwJJbLJCbMJAwPJwIKwJKwKKbLKBbMKAwPKwILbJLAbKLAwPLwIMwJMwKMwNMwOMwPMwKNwLNwMNwNN",
    "wFDwGDwHDwIDwJDwKDwLDwMDwNDwODwPDwQDwRDwSDwTDwUDwFEbPECwQEwUEwFFhHFAhJFIhLFAhNFIbPFCbQFBbRFAwUFwFGhJGBhNGBbPGCbQGBwUGwFHhHHIpLHbPHCbQHBbRHCwUHwFIhHIJbPICbQIAbRICwUIwFJhHJBhJJEhKJCbMJBbNJBbPJCbQJAbRJBwUJwFKbPKCwQKwUKwFLwGLwHLwILwJLwKLwLLwMLwNLwOLwPLwQLwRLwSLwTLwUL",
    "wHDwIDwJDwKDwLDwMDwNDwODwPDwQDwRDwSDwTDwHEbPEBhQEIwTEwHFbPFBhQFJwTFwHGbJGCbKGCbLGCbMGCbNGAbOGAbPGBhQGJcRGBwTGwHHbJHCbPHBhQHBhRHEhSHCwTHwHIbJICwQIwRIwSIwTIwHJcLJBcMJCpOJwQJwHKwQKwHLwILwJLwKLwLLwMLwNLwOLwPLwQL",
    "wGDwHDwIDwJDwKDwLDwMDwNDwODwPDwQDwRDwSDwTDwGEwTEwGFhIFIwTFwGGhIGNhJGCdNGIwTGwGHhIHBdNHBwTHwGIwTIwGJpJJwTJwGKwTKwGLwHLwILwJLwKLwLLwMLwNLwOLwPLwQLwRLwSLwTL",
    "wFEwGEwHEwIEwJEwKEwLEwMEwNEwOEwPEwQEwREwSEwTEwUEwFFbRFAbSFAbTFAwUFwVFwFGhNGMhOGGhPGKbRGAbSGBbTGAwVGwFHhIHApLHhNHJhPHJbRHAbSHAbTHAwUHwVHwFIhNIFhOIGhPIDwRIwSIwTIwUIwFJwRJwFKwGKwHKwIKwJKwKKwLKwMKwNKwOKwPKwQKwRK",
    "wFEwGEwHEwIEwJEwKEwLEwMEwNEwOEwPEwQEwREwSEwTEwUEwFFpLFbRFAbSFAbTFAwUFwFGhHGMhIGGhJGKdKGIrMGIbRGAbSGBbTGAwUGwFHhHHJhJHJdKHBrMHBhOHAbRHAbSHAbTHAwUHwFIhHIFhIIGhJIDwRIwSIwTIwUIwFJwRJwFKwGKwHKwIKwJKwKKwLKwMKwNKwOKwPKwQKwRK"
}

floors = {
    "fHFGFfNFHD","fHFHFfNFHD","fGFOF","fIFMF","fGFOF","","","fHCIIfJKGD","","fHDNFfHDJJ","","","fGEOEfGHMD"
}

levelMap = {
    {
        {i=1, x=1, y=1, right={2, 1}},
    },
    {
        {i=2, x=3, y=1, left={1, 1}, down={3, 1}},
    },
    {
        {i=12, x=3, y=3, up={2, 1}}
    }
    -- world1 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13}
}